### PR TITLE
Add additional hand images

### PR DESCRIPTION
**Pull request by sktometometo**
Add additional hand images `hand_color_in_hand_depth_frame`, `hand_depth_in_hand_color_frame` so that point cloud can be genereted with `depth_image_proc`

### CODE REVIEW

**Comment by k-okada** [comment]
Are you tring to process depth image? if you simply would like to get 3d pose of the image, plesae check to see if spot-sdk already provide the service.
If you would like to get 3d pose of detected object, please consider using https://github.com/k-okada/spot_ros-arm/blob/arm/spot_driver/scripts/ncb_provider and https://github.com/k-okada/jsk_robot/blob/spot_arm/jsk_spot_robot/jsk_spot_startup/launch/include/perception.launch

**Comment by sktometometo** [comment]
I want to detect the top plane of a table. For this, we already have detection pipeline based of jsk_pcl_ros. So I want to use PointCloud2 message to reuse it.

**Comment by sktometometo** [comment]
@k-okada There are some users already for this PR. So could you review this?

See the pose of @a-ichikura at Spot space of Google Chat.

**Comment by sktometometo** [comment]
Thanks!

**Pull request merged**
